version: '3.8'

services:
  backend:
    build: .
    container_name: furniture_backend
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-xv9rj3h6@1f8%g^!u)c=^&wd592wlp+gc6$$rpb-4cy7*ci=z^o
      - ALLOWED_HOSTS=localhost,127.0.0.1
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
